version: '2'
services:
    web:
        build: .
        ports:
            - "5048:5048"
        networks:
          - web
        volumes:
            - .:/myapp
        restart: always
        labels:
          traefik.enable: true
          traefik.port: 5048
          traefik.frontend.rule: "Host:shruggie.janamarie.dev,404.janamarie.dev,404.otter.jetzt"
          traefik.frontend.redirect.entryPoint: "https"
          traefik.docker.network: web

networks:
  web:
    external: true


